on: [push]

name: check
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/degica/rails-buildpack:3.1
    steps:
    - uses: actions/checkout@v3
    - run: ruby check.rb
